### PR TITLE
fix(isInSubnet): Throw errors on invalid subnet IPs

### LINKED ISSUE #6: `isInSubnet` not throwing on invalid subnets
The `isInSubnet` docs state
> Will throw an Error if the address or subnet are not valid IP addresses 

but some subnets with invalid IP address components do not cause the function to throw. Here are an examples with an IPv4-like thing and IPv6-like thing:
```js
> isIP('1.352352352')
0
> isInSubnet('1.3.3.4', '1.352352352/32')
false
> isIP('11:22:33:44:55:66:77:88:99:1010')
0
> isInSubnet('1.3.3.4', '11:22:33:44:55:66:77:88:99:1010/32')
false
```

Notably, the specialized functions `IPv4.isInSubnet` and `IPv6.isInSubnet` don't exhibit issue:
```js
> IPv4.isInSubnet('1.3.3.4', '1.352352352/32')
Thrown:
Error: not a valid IPv4 address: 1.352352352
> IPv6.isInSubnet('::ffff:1.2.3.4', '11:22:33:44:55:66:77:88:99:1010/32')
Thrown:
Error: not a valid IPv6 address: 11:22:33:44:55:66:77:88:99:1010
```

P.S. Thank you for writing such a well-documented and single-purpose package!

### PR DESCRIPTION
**Pull request by spencerwilson-optimizely**
- Ensure `isInSubnet` throws if any of the given subnets lack valid IP addresses

Fixes #6

### CODE REVIEW

**Comment by spencerwilson-optimizely** [comment]
Hm, this doesn't fix
```
> isInSubnet('1.2.233333.4', '2001:db8::/32')
false
```
which should also throw.

File: src/index.ts [hunk 1]
```diff
@@ -9,38 +9,39 @@ export { IPv4, IPv6 };
...
  * @param address the IPv4 or IPv6 address to check
  * @param subnet the IPv4 or IPv6 CIDR to test (or an array of them)
- * @throws if the address or subnet are not valid IP addresses, or the CIDR prefix length
+ * @throws if any of the address or subnet(s) are not valid IP addresses, or the CIDR prefix length
  *  is not valid
  */
 export function isInSubnet(address: string, subnetOrSubnets: string | string[]): boolean {
   if (!Array.isArray(subnetOrSubnets)) {
     return isInSubnet(address, [subnetOrSubnets]);
   }
```
Comment (natesilva) [inline src/index.ts]:
```suggestion
  if (!util.isIP(address)) {
    throw new Error(`not a valid IPv4 or IPv6 address: ${address}`);
  }
```

File: src/index.ts [hunk 2]
```diff
@@ -9,38 +9,39 @@ export { IPv4, IPv6 };
  * Test if the given IP address is contained in the specified subnet.
  * @param address the IPv4 or IPv6 address to check
  * @param subnet the IPv4 or IPv6 CIDR to test (or an array of them)
- * @throws if the address or subnet are not valid IP addresses, or the CIDR prefix length
+ * @throws if any of the address or subnet(s) are not valid IP addresses, or the CIDR prefix length
```
Comment (natesilva) [inline src/index.ts]: wrap at 90 please

File: test/index.ts [hunk 3]
```diff
@@ -83,4 +83,17 @@ describe('general tests', () => {
     assert.strictEqual(isSpecial('::'), true);
     assert.strictEqual(isSpecial('::ffff:127.0.0.1'), true);
   });
+
```
Comment (natesilva) [inline test/index.ts]:
```suggestion
  it('should throw on invalid IPs', () => {
    assert.throws(() => isInSubnet('1.2.233333.4', '2001:db8::/32'));
    assert.throws(() => isInSubnet('11:22:33:44:55', '2001:db8::/32'));
    assert.throws(() => isInSubnet('1.352352352', '0.0.0.0/0'));
    assert.throws(() =>
      isInSubnet('11:22:33:44:55:66:77:88:99:1010', '2001:db8:f53a::1:1/64')
    );
```

**Comment by spencerwilson-optimizely** [comment]
Whoops, hadn't reloaded and seen your suggestions. One sec.

**Comment by spencerwilson-optimizely** [comment]
Okay, should be good to go. Prettier'd, linted, tests passing.

**Comment by natesilva** [comment]
Thank you
